"""empty message

Revision ID: 1dee8540542a
Revises: 74f9a5daae35
Create Date: 2022-01-29 13:12:49.790366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dee8540542a'
down_revision = '74f9a5daae35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilepic', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilepic')
    # ### end Alembic commands ###
