"""added pic

Revision ID: 283907f235fc
Revises: b2ae9574a806
Create Date: 2022-01-28 23:29:00.557985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283907f235fc'
down_revision = 'b2ae9574a806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
