"""added username

Revision ID: 39309c04c0d2
Revises: 2b7c27439092
Create Date: 2022-01-23 00:38:53.664219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39309c04c0d2'
down_revision = '2b7c27439092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
