"""add profile pic

Revision ID: 74f9a5daae35
Revises: 283907f235fc
Create Date: 2022-01-29 13:08:15.291065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f9a5daae35'
down_revision = '283907f235fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilepic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilepic')
    # ### end Alembic commands ###
